[package]
name = "battleship_bot"
version = "1.0.0"
edition = "2021"
license-file = "LICENSE"
description = ""

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"
